---
title: "viz_and_eda"
author: "Xin  He"
date: "9/26/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)
```

## create the weather data
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


## create a ggplot
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()
```

alternate the way of making this plot
```{r}
weather_df %>% 
  ggplot(aes(x  = tmin, y = tmax)) + 
  geom_point()
```

saving initial plots
```{r}
scatterplot = 
  weather_df %>% 
  ggplot(aes(x  = tmin, y = tmax)) + 
  geom_point()

scatterplot
```


## adding color
```{r}
weather_df %>% 
  ggplot(aes(x  = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .4)
```



## why do 'aes' positions matter (color= in different positions)

first
```{r}
weather_df %>% 
  ggplot(aes(x  = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .4) +
  geom_smooth(se = FALSE)
```

vs

```{r}
weather_df %>% 
  ggplot(aes(x  = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .4) +
  geom_smooth(se = FALSE)
```




##  facet
```{r}
weather_df %>% 
  ggplot(aes(x  = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .4) +
  geom_smooth(se = FALSE) +
  facet_grid(~ name)
```


```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .4) +
  geom_smooth(size = 2, se = FALSE)
```

## some extra stuff
```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_smooth(size = 2, se = FALSE)
```


2d density
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_bin2d()
```

# install hexbin
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()


## more kinds of plots
```{r}
weather_df %>%
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram() +
  facet_grid(~name)
```

density plot!
```{r}
weather_df %>%
  ggplot(aes(x = tmax, fill = name)) +
  geom_density(alpha = .3) 
```


## box plots
```{r}
weather_df %>%
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()
```

## violin plot
```{r}
weather_df %>%
  ggplot(aes(x = name, y = tmax)) +
  geom_violin()
```


## ridge plots
**compare between groups**
```{r}
weather_df %>%
  ggplot(aes(x = tmax, y = name)) +
  geom_density_ridges()
```







